### ISSUE TITLE
Videos are not getting uploaded when `videoUploadOnPasses` is true

### ISSUE THREAD

**Issue by agoldis** [currents-dev/cypress-cloud#101]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line
Reported via in-app chat

```

</details>

### Describe the bug

Reported via in-app chat  - customer has `videoUploadOnPasses: true` and no videos are getting uploaded

### Expected behavior

Videos should appear

### Command and Setup

n/a

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by mirobo** [comment]
On sorry-cypress 2.5.3 I saw that when I run tests with cypress-cloud 1.5.0 and 1.5.3, the screenshots and videos are uploaded in a way that sorry-cypress delivers them as application/json rather than binary/octet-stream. Is this the same issue?

Wrong (Cypress 12.6.0 + cypress-cloud 1.5.3):
![image](https://user-images.githubusercontent.com/78788210/226564945-45b60453-e3c0-48ae-99ae-a5148860b43a.png)

![image](https://user-images.githubusercontent.com/78788210/226564996-3e5249f4-ebb9-4244-be59-b508c5ed13d9.png)

Correct (Test was run with cy2 and older version of Cypress):
![image](https://user-images.githubusercontent.com/78788210/226565137-1db52b8c-3c2e-4887-bc93-fc186f18cd46.png)

I think it worked (need to check) when I ran tests with **cypress-cloud 1.4.4 via npx cypress-cloud**..

**Comment by mirobo** [comment]
I can confirm that cypress-cloud 1.4.4 uploads screenshots and videos correctly to sorry-cypress (2.5.3) and when using 1.5.3, the artifacts are delivered as application/json. Cypress 12.6.0

**Comment by agoldis** [comment]
Not an issue with the package. Internal currents bug.
