### ISSUE TITLE
When using cypress-cloud with the cypress-testrail plugin, testrails runs are created for each spec file and not the entire run

### ISSUE THREAD

**Issue by jwohlfahrt** [currents-dev/cypress-cloud#128]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line


```

</details>
### Describe the bug

I am using the latest version of the cypress-testrail plugin (2.7.0) with the latest version of the cypress-cloud plugin (1.7.4). I have the testrail plugin configured to create a testrail run at the beginning of a testrun. This works fine when not combined with cypress-cloud, but when I add the cloud plugin to the run, each spec file generates its own run, as if a new cypress run is kicked off internally after each specfile. I was curious if this could be related to the way that cypress-cloud handles run orchestration, and whether under the hood it create a run per spec. For context, the cypress-testrail plugin uses the `before:run` hook to create the testrail run: https://github.com/boxblinkracer/cypress-testrail/blob/master/src/Reporter.js#L59. Any help would be appreciated!

### Expected behavior

When used with cypress-cloud, the cypress-testrail plugin should only create a single testrail run for a given cypress run.

### Command and Setup

Sample config setup:
```
setupNodeEvents: async(on, config) => {
      new TestRailReporter(on, config)
          .register();

      await cloudPlugin(on, config);

      return config;
    }
```

### Full log and debug output

<details>

```
// Put your logs below this line
N/a for this issue

```

</details>

**Comment by agoldis** [comment]
@jwohlfahrt 
Thanks for reporting the issue!

cypress-cloud runs cypress in offline mode - i.e. it starts cypress from scratch on every iteration. 

testrail creates a new run on every new cypress invocation, so starting cypress multiple times creates a new run in testrail as well. 

One solution can be setting `TESTRAIL_RUN_ID` explicitly for each new cypress run: https://github.com/boxblinkracer/cypress-testrail/blob/4ac88b5587e1b7cba0228d5f25b7b257e56a07ec/src/services/ConfigService.js#L225

For example, it can have the same value as the [CI build ID](https://currents.dev/readme/guides/cypress-ci-build-id)


P.S.

I am curious if this issue happens when running cypress in parallel mode - if the cypress starts on multiple machines (for the same cypress run), several testrail runs should be created as well.

**Comment by agoldis** [comment]
@jwohlfahrt 
Closing the issue, please reopen if setting `TESTRAIL_RUN_ID` doesn't work
