### ISSUE TITLE
[CSR-638] Cypress-grep compatibilty

### ISSUE THREAD

**Issue by agoldis** [currents-dev/cypress-cloud#50]
See https://sorry-cypress.slack.com/archives/C04F7LJ1E3H/p1671443824388969

The plugin is widely used, and we need to restore its functionality. I don't have many details except for the user's report. 

![Screenshot 2022-12-19 at 10 36 39 (1)](https://user-images.githubusercontent.com/1637928/208404139-f5521866-33cd-4040-9408-1df0823933f0.jpg)

**Comment by Rikkun-1** [comment]
I am using:
cypress: 12.16.0
@cypress/grep: 3.1.5
sorry-cypress: 2.5.1
cypress-cloud: 1.8.2

Existing in repo test case is very simple and does not describe real world usage:
- https://github.com/currents-dev/cypress-cloud/commit/5d7f36df3c770cad4ea15fb1e75b3aa320402c93#diff-6bd6fd4f71bae5e0b20dfcc2a86a659b57a657f546d2bdf033b7825d985f9376R1-R17
- https://github.com/currents-dev/cypress-cloud/commit/5d7f36df3c770cad4ea15fb1e75b3aa320402c93#diff-5ba646cdcf865c7d8146e78da174190a6cc056645ad7ee916c4df28844b4ed0aR1-R5.

There is only one spec file and it satisfies grepTags.
But if we have two spec files and one of them does not contain any case that satisfies grepTags then run will fail.

For example if we have following configuration where we have two files each with different tag:
```js
// testTagA.spec.js
it('My test', { tags: ['@tagA'] } () => {
  // ...
});

// testTagB.spec.js
it('My test', { tags: ['@tagB'] } () => {
  // ...
});
```
then if we run it like this:
`npx cypress-cloud --env grepTags=@tagB ...`

Then result will be like this:
```
Running: cypress/e2e/testTagA.spec.js (1/2)
@cypress/grep: filtering using tag(s) "@tagB"
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

> /home/.../projects/frontend/cypress/e2e/testTagA.spec.js
WARNING  Cypress runner failed with message: "Could not find Cypress test run results"
WARNING  The following spec files will be marked as failed: 
- /home/.../projects/frontend/cypress/e2e/testTagA.spec.js

Reporting results and artifacts in background...  
```

I think thats because cy2 implementation tried to run all specs in one `cypress run`.
So when one of specs is filtered out by @cypress/grep there is still another one that will be run.

But cypress-cloud works differently.
It runs every spec file in separate `cypress run` command.
Thus, there is only one spec file per run so when cypress-grep filters out that single file, cypress fails with an error that there is no test cases that satisfy spec and tag filtering.
Cypress programmed to fail if it can't find any test case in entire run.
So if, instead of one big run with all specs, we create many runs with one spec, then all runs that don't match the grep pattern will fail.

I can't use @cypress/grep after I moved from cy2 to cypress-cloud.
This issue makes @cypress/grep incompatible with cypress-cloud at the moment which is very sad for me.
@cypress/grep is crucial for big projects with many tests.

I would be very happy if this issue will be resolved and @cypress/grep will become compatible again.
Thanks in advance for your time.

**Comment by agoldis** [comment]
@Rikkun-1 thanks for reporting that issue - good catch, we'll issue a fix soon

**Comment by Rikkun-1** [comment]
> I am using: cypress: 12.16.0 @cypress/grep: 3.1.5 sorry-cypress: 2.5.1 cypress-cloud: 1.8.2
> 
> Existing in repo test case is very simple and does not describe real world usage:
> 
> * [5d7f36d#diff-6bd6fd4f71bae5e0b20dfcc2a86a659b57a657f546d2bdf033b7825d985f9376R1-R17](https://github.com/currents-dev/cypress-cloud/commit/5d7f36df3c770cad4ea15fb1e75b3aa320402c93#diff-6bd6fd4f71bae5e0b20dfcc2a86a659b57a657f546d2bdf033b7825d985f9376R1-R17)
> * [5d7f36d#diff-5ba646cdcf865c7d8146e78da174190a6cc056645ad7ee916c4df28844b4ed0aR1-R5](https://github.com/currents-dev/cypress-cloud/commit/5d7f36df3c770cad4ea15fb1e75b3aa320402c93#diff-5ba646cdcf865c7d8146e78da174190a6cc056645ad7ee916c4df28844b4ed0aR1-R5).
> 
> There is only one spec file and it satisfies grepTags. But if we have two spec files and one of them does not contain any case that satisfies grepTags then run will fail.
> 
> For example if we have following configuration where we have two files each with different tag:
> 
> ```js
> // testTagA.spec.js
> it('My test', { tags: ['@tagA'] } () => {
>   // ...
> });
> 
> // testTagB.spec.js
> it('My test', { tags: ['@tagB'] } () => {
>   // ...
> });
> ```
> 
> then if we run it like this: `npx cypress-cloud --env grepTags=@tagB ...`
> 
> Then result will be like this:
> 
> ```
> Running: cypress/e2e/testTagA.spec.js (1/2)
> @cypress/grep: filtering using tag(s) "@tagB"
> Can't run because no spec files were found.
> 
> We searched for specs matching this glob pattern:
> 
> > /home/.../projects/frontend/cypress/e2e/testTagA.spec.js
> WARNING  Cypress runner failed with message: "Could not find Cypress test run results"
> WARNING  The following spec files will be marked as failed: 
> - /home/.../projects/frontend/cypress/e2e/testTagA.spec.js
> 
> Reporting results and artifacts in background...  
> ```
> 
> I think thats because cy2 implementation tried to run all specs in one `cypress run`. So when one of specs is filtered out by @cypress/grep there is still another one that will be run.
> 
> But cypress-cloud works differently. It runs every spec file in separate `cypress run` command. Thus, there is only one spec file per run so when @cypress/grep filters out that single file, cypress fails with an error that there is no test cases that satisfy spec and tag filtering. Cypress programmed to fail if it can't find any test case in entire run. So if, instead of one big run with all specs, we create many runs with one spec, then all runs that don't match the grep pattern will fail.
> 
> I can't use @cypress/grep after I moved from cy2 to cypress-cloud. This issue makes @cypress/grep incompatible with cypress-cloud at the moment which is very sad for me. @cypress/grep is crucial for big projects with many tests.
> 
> I would be very happy if this issue will be resolved and @cypress/grep will become compatible again. Thanks in advance for your time.

I want to add an important note to this comment.
I was wrong, the @cypress/grep plugin is not completely incompatible with cypress-cloud.
I forgot that I added the [grepOmitFiltered](https://www.npmjs.com/package/@cypress/grep#omit-filtered-tests-grepomitfiltered) option to my config file a long time ago.
Adding this will not only skip tests that don't match the tags, but it will remove those tests from the run entirely, resulting in the error described above.
@cypress/grep plugin works fine if you don't use grepFilterSpecs, grepOmitFiltered options.
Tests that don't match the grep pattern will simply be marked as skipped, and the runner will be fine even if all tests in the file are skipped.

**Comment by agoldis** [comment]
A small correction - the issue is only relevant when `grepFilterSpecs` is activated, `grepOmitFiltered` doesn't matter

**Comment by agoldis** [comment]
@Rikkun-1 ?

**Comment by Rikkun-1** [comment]
Sorry for the delay, @agoldis. I was busy with work.
Your workaround works great.
I ran into another issue with cypress/@grep when tried to test it with grepFilterSpecs but it's easy to solve with this comment https://github.com/cypress-io/cypress/issues/27216#issuecomment-1624119242.

Thanks a lot for your workaround, it's really important for test suite management.

**Comment by agoldis** [comment]
@Rikkun-1 awesome! 
I updated to documentation with a reference to this issue: https://github.com/currents-dev/cypress-cloud/blob/main/.github/README.md#usage-with-cypressgrep
